name: muteapp
options:
  bundleIdPrefix: com.billimek
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 3.1.0
targets:
  muteapp:
    type: application
    platform: macOS
    sources:
      - muteapp
    info:
      path: muteapp/Info.plist
      properties:
        LSUIElement: true
        LSMinimumSystemVersion: "13.0"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSHumanReadableCopyright: "© 2026 Jeff Billimek"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.billimek.muteapp
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: "2"
        SWIFT_VERSION: "5.0"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: muteapp/muteapp.entitlements
        CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
        COMBINE_HIDPI_IMAGES: YES
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: muteapp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_DEBUG_DYLIB: NO
        ENABLE_DEBUG_DYLIB_OVERRIDE: NO
    dependencies:
      - package: KeyboardShortcuts
